# Use the official PyTorch image with CUDA support and Python 3.10
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

# Set working directory
WORKDIR /homa

# Install `uv` globally
RUN pip install --no-cache-dir --upgrade pip && pip install uv

# Copy dependencies from the parent directory
COPY ../requirements.txt ../pyproject.toml ./

# Create virtual environment and install dependencies using `uv`
RUN uv venv .venv && \
    uv pip install -r requirements.txt

# Copy the rest of the application files from the parent directory
COPY ../ ./

# Default command
CMD ["bash"]
